### ISSUE TITLE
Do you have Function.identity()?

### ISSUE THREAD

**Issue by BattleShipPark** [aNNiMON/Lightweight-Stream-API#89]
Although its implementation is not complicated, I'd like to check it exists or not.
Thanks.

**Comment by aNNiMON** [comment]
@BattleShipPark [it exists in `UnaryOperator.Util` class](https://github.com/aNNiMON/Lightweight-Stream-API/blob/fe82a08a79be67d93abeef6e0c8ce7787efd504f/stream/src/main/java/com/annimon/stream/function/UnaryOperator.java#L21-L28).

Since interface `UnaryOperator<T>` extends `Function<T, T>`, you can use  `UnaryOperator<T> identity()` as `Function<T, T> identity()` replacement.

**Comment by BattleShipPark** [comment]
Thanks!
