### ISSUE TITLE
Where is Comparator.reversed()?

### ISSUE THREAD

**Issue by BattleShipPark** [aNNiMON/Lightweight-Stream-API#95]
Hi,
I'd like to know where Comparator.reversed() is. 
Thanks!

**Comment by aNNiMON** [comment]
@BattleShipPark there is no backported methods of `Comparator`. But it's idea to backport them. Thanks!

**Comment by aNNiMON** [comment]
@BattleShipPark you can use [Collections.reverseOrder(comparator)](https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#reverseOrder(java.util.Comparator)). It has been intruduced in Java 1.5 and exists in Android API level 1.

Since `default` methods are introduced in Java 8, I can only create something like `ComparatorCompat.reversed(comparator)` instead of  `comparator.reversed()`. So, for reversed order, please, use `Collections` class.

Other Comparator's methods, such as `thenComparing`, `comparing`, etc, I will implement soon.

**Comment by BattleShipPark** [comment]
I will be waiting for them. Thanks
